name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64, armv7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2  # 更新到 v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # 更新到 v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Build and push multi-architecture Docker image
        uses: docker/build-push-action@v3  # 更新到 v3
        with:
          context: .
          push: true
          tags: cqshushu/iptv-hls:latest
          platforms: linux/${{ matrix.architecture }}
